service: desafio-infra-gu

frameworkVersion: "3"

plugins:
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless/provider/environment.yml)}


custom: ${file(./serverless/custom/variables.yml)}

resources:
  - ${file(./serverless/resources/dynamodb/table.test.yml)}
  - ${file(./serverless/resources/dynamodb/table.yml)}
  - ${file(./serverless/resources/ssm/parameters.yml)}

functions:







